import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "animate.css";
import SessionWrapper from "./_components/SessionWrapper";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import { Toaster } from "sonner";
import { ColorThemeProvider } from "./_components/theme/color-provider"; // ✅ import your color provider
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Web Developer Timekeeping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  font-space  bg-background text-foreground min-h-screen flex flex-col`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <ColorThemeProvider>
            <SessionWrapper>
              <Navbar />
              {children}
              <Toaster
                position="bottom-right"
                richColors
                theme="dark"
              />
              <Footer />
            </SessionWrapper>
          </ColorThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
