export const quotes = [
  {
    q: "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.",
    a: "Thich Nhat Hanh",
    c: "82",
    h: "\u003Cblockquote\u003E&ldquo;Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.&rdquo; &mdash; \u003Cfooter\u003EThich Nhat Hanh\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Obstacles are those frightful things you see when you take your eyes off your goals.",
    a: "Sydney Smith",
    c: "84",
    h: "\u003Cblockquote\u003E&ldquo;Obstacles are those frightful things you see when you take your eyes off your goals.&rdquo; &mdash; \u003Cfooter\u003ESydney Smith\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Life is a challenge, meet it! Life is a dream, realize it! Life is a game, play it! Life is love, enjoy it!",
    a: "Sathya Sai Baba",
    c: "107",
    h: "\u003Cblockquote\u003E&ldquo;Life is a challenge, meet it! Life is a dream, realize it! Life is a game, play it! Life is love, enjoy it!&rdquo; &mdash; \u003Cfooter\u003ESathya Sai Baba\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "One machine can do the work of fifty ordinary men. No machine can do the work of one extraordinary man.",
    a: "Elbert Hubbard",
    c: "103",
    h: "\u003Cblockquote\u003E&ldquo;One machine can do the work of fifty ordinary men. No machine can do the work of one extraordinary man.&rdquo; &mdash; \u003Cfooter\u003EElbert Hubbard\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "The only limits in our life are those we impose on ourselves.",
    a: "Bob Proctor",
    c: "61",
    h: "\u003Cblockquote\u003E&ldquo;The only limits in our life are those we impose on ourselves.&rdquo; &mdash; \u003Cfooter\u003EBob Proctor\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Strive for excellence, not perfection, because we don't live in a perfect world.",
    a: "Joyce Meyer",
    c: "80",
    h: "\u003Cblockquote\u003E&ldquo;Strive for excellence, not perfection, because we don't live in a perfect world.&rdquo; &mdash; \u003Cfooter\u003EJoyce Meyer\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Men go to far greater lengths to avoid what they fear than to obtain what they desire.",
    a: "Dan Brown",
    c: "86",
    h: "\u003Cblockquote\u003E&ldquo;Men go to far greater lengths to avoid what they fear than to obtain what they desire.&rdquo; &mdash; \u003Cfooter\u003EDan Brown\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Well done is better than well said.",
    a: "Benjamin Franklin",
    c: "35",
    h: "\u003Cblockquote\u003E&ldquo;Well done is better than well said.&rdquo; &mdash; \u003Cfooter\u003EBenjamin Franklin\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Learn only how to avoid seeking for and attaching yourselves to anything.",
    a: "Huang Po",
    c: "73",
    h: "\u003Cblockquote\u003E&ldquo;Learn only how to avoid seeking for and attaching yourselves to anything.&rdquo; &mdash; \u003Cfooter\u003EHuang Po\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Failing is another stepping stone to greatness.",
    a: "Oprah Winfrey",
    c: "47",
    h: "\u003Cblockquote\u003E&ldquo;Failing is another stepping stone to greatness.&rdquo; &mdash; \u003Cfooter\u003EOprah Winfrey\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Chop your own wood and it will warm you twice. ",
    a: "Henry Ford",
    c: "47",
    h: "\u003Cblockquote\u003E&ldquo;Chop your own wood and it will warm you twice. &rdquo; &mdash; \u003Cfooter\u003EHenry Ford\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "A person hears only what they understand.",
    a: "Johann Wolfgang von Goethe",
    c: "41",
    h: "\u003Cblockquote\u003E&ldquo;A person hears only what they understand.&rdquo; &mdash; \u003Cfooter\u003EJohann Wolfgang von Goethe\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "True knowledge exists in knowing that you know nothing.",
    a: "Socrates",
    c: "55",
    h: "\u003Cblockquote\u003E&ldquo;True knowledge exists in knowing that you know nothing.&rdquo; &mdash; \u003Cfooter\u003ESocrates\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Youth ages, immaturity is outgrown, ignorance can be educated, and drunkenness sobered, but stupid lasts forever.",
    a: "Aristophanes",
    c: "113",
    h: "\u003Cblockquote\u003E&ldquo;Youth ages, immaturity is outgrown, ignorance can be educated, and drunkenness sobered, but stupid lasts forever.&rdquo; &mdash; \u003Cfooter\u003EAristophanes\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "The secret of happiness is not in doing what you like but in liking what you have to do.",
    a: "Sathya Sai Baba",
    c: "88",
    h: "\u003Cblockquote\u003E&ldquo;The secret of happiness is not in doing what you like but in liking what you have to do.&rdquo; &mdash; \u003Cfooter\u003ESathya Sai Baba\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Over time, loneliness gets inside you and doesn't go away.",
    a: "Carlos Ruiz Zafon",
    c: "58",
    h: "\u003Cblockquote\u003E&ldquo;Over time, loneliness gets inside you and doesn't go away.&rdquo; &mdash; \u003Cfooter\u003ECarlos Ruiz Zafon\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "There is no path to Peace. Peace is the path.",
    a: "Dan Millman",
    c: "45",
    h: "\u003Cblockquote\u003E&ldquo;There is no path to Peace. Peace is the path.&rdquo; &mdash; \u003Cfooter\u003EDan Millman\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "It is the greatest of all mistakes to do nothing because you can only do little; do something.",
    a: "Sydney Smith",
    c: "94",
    h: "\u003Cblockquote\u003E&ldquo;It is the greatest of all mistakes to do nothing because you can only do little; do something.&rdquo; &mdash; \u003Cfooter\u003ESydney Smith\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Others can stop you temporarily - you are the only one who can do it permanently.",
    a: "Zig Ziglar",
    c: "81",
    h: "\u003Cblockquote\u003E&ldquo;Others can stop you temporarily - you are the only one who can do it permanently.&rdquo; &mdash; \u003Cfooter\u003EZig Ziglar\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Man should fear never beginning to live.",
    a: "Marcus Aurelius",
    c: "40",
    h: "\u003Cblockquote\u003E&ldquo;Man should fear never beginning to live.&rdquo; &mdash; \u003Cfooter\u003EMarcus Aurelius\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "No matter how much preparation we do, in the real tests of our lives, we'll be in unfamiliar terrain.",
    a: "Josh Waitzkin",
    c: "101",
    h: "\u003Cblockquote\u003E&ldquo;No matter how much preparation we do, in the real tests of our lives, we'll be in unfamiliar terrain.&rdquo; &mdash; \u003Cfooter\u003EJosh Waitzkin\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Everyone has a sense of humor. If you don't laugh at jokes, you probably laugh at opinions.",
    a: "Criss Jami",
    c: "91",
    h: "\u003Cblockquote\u003E&ldquo;Everyone has a sense of humor. If you don't laugh at jokes, you probably laugh at opinions.&rdquo; &mdash; \u003Cfooter\u003ECriss Jami\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Embody what you teach, and teach only what you have embodied.",
    a: "Dan Millman",
    c: "61",
    h: "\u003Cblockquote\u003E&ldquo;Embody what you teach, and teach only what you have embodied.&rdquo; &mdash; \u003Cfooter\u003EDan Millman\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Not engaging in ignorance is wisdom. ",
    a: "Bodhidharma",
    c: "37",
    h: "\u003Cblockquote\u003E&ldquo;Not engaging in ignorance is wisdom. &rdquo; &mdash; \u003Cfooter\u003EBodhidharma\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Courage is the willingness to engage in a risk-taking behavior regardless of whether the consequences are unknown or possibly adverse.",
    a: "Alfred Adler",
    c: "134",
    h: "\u003Cblockquote\u003E&ldquo;Courage is the willingness to engage in a risk-taking behavior regardless of whether the consequences are unknown or possibly adverse.&rdquo; &mdash; \u003Cfooter\u003EAlfred Adler\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "A little progress each day adds up to big results.",
    a: "Unknown",
    c: "50",
    h: "\u003Cblockquote\u003E&ldquo;A little progress each day adds up to big results.&rdquo; &mdash; \u003Cfooter\u003EUnknown\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Even in the grave, all is not lost.",
    a: "Edgar Allan Poe",
    c: "35",
    h: "\u003Cblockquote\u003E&ldquo;Even in the grave, all is not lost.&rdquo; &mdash; \u003Cfooter\u003EEdgar Allan Poe\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Life happens in the river, not the shore.",
    a: "Maxime Lagace",
    c: "41",
    h: "\u003Cblockquote\u003E&ldquo;Life happens in the river, not the shore.&rdquo; &mdash; \u003Cfooter\u003EMaxime Lagace\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "The wise warrior avoids the battle.",
    a: "Sun Tzu",
    c: "35",
    h: "\u003Cblockquote\u003E&ldquo;The wise warrior avoids the battle.&rdquo; &mdash; \u003Cfooter\u003ESun Tzu\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Inner peace is when you realize that, in the end, nothing matters.",
    a: "Maxime Lagace",
    c: "66",
    h: "\u003Cblockquote\u003E&ldquo;Inner peace is when you realize that, in the end, nothing matters.&rdquo; &mdash; \u003Cfooter\u003EMaxime Lagace\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Cry. Forgive. Learn. Move on. Let your tears water the seeds of your future happiness.",
    a: "Steve Maraboli",
    c: "86",
    h: "\u003Cblockquote\u003E&ldquo;Cry. Forgive. Learn. Move on. Let your tears water the seeds of your future happiness.&rdquo; &mdash; \u003Cfooter\u003ESteve Maraboli\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.",
    a: "Ayn Rand",
    c: "100",
    h: "\u003Cblockquote\u003E&ldquo;Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.&rdquo; &mdash; \u003Cfooter\u003EAyn Rand\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Great thoughts speak only to the thoughtful mind, but great actions speak to all mankind.",
    a: "Theodore Roosevelt",
    c: "89",
    h: "\u003Cblockquote\u003E&ldquo;Great thoughts speak only to the thoughtful mind, but great actions speak to all mankind.&rdquo; &mdash; \u003Cfooter\u003ETheodore Roosevelt\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "True prayer has no set form.",
    a: "Morihei Ueshiba",
    c: "28",
    h: "\u003Cblockquote\u003E&ldquo;True prayer has no set form.&rdquo; &mdash; \u003Cfooter\u003EMorihei Ueshiba\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Success is never final, failure is never fatal. It's courage that counts.",
    a: "John Wooden",
    c: "73",
    h: "\u003Cblockquote\u003E&ldquo;Success is never final, failure is never fatal. It's courage that counts.&rdquo; &mdash; \u003Cfooter\u003EJohn Wooden\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "There are no ordinary moments.",
    a: "Dan Millman",
    c: "30",
    h: "\u003Cblockquote\u003E&ldquo;There are no ordinary moments.&rdquo; &mdash; \u003Cfooter\u003EDan Millman\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "To some degree, you control your life by controlling your time.",
    a: "Conrad Hilton",
    c: "63",
    h: "\u003Cblockquote\u003E&ldquo;To some degree, you control your life by controlling your time.&rdquo; &mdash; \u003Cfooter\u003EConrad Hilton\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Truth is like the sun. You can shut it out for a time, but it ain't going away.",
    a: "Elvis Presley",
    c: "79",
    h: "\u003Cblockquote\u003E&ldquo;Truth is like the sun. You can shut it out for a time, but it ain't going away.&rdquo; &mdash; \u003Cfooter\u003EElvis Presley\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "What most people need to learn in life is how to love people and use things instead of using people and loving things.",
    a: "Unknown",
    c: "118",
    h: "\u003Cblockquote\u003E&ldquo;What most people need to learn in life is how to love people and use things instead of using people and loving things.&rdquo; &mdash; \u003Cfooter\u003EUnknown\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "The hard path is often the right one. The river teaches more than the shore.",
    a: "Maxime Lagace",
    c: "76",
    h: "\u003Cblockquote\u003E&ldquo;The hard path is often the right one. The river teaches more than the shore.&rdquo; &mdash; \u003Cfooter\u003EMaxime Lagace\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Turn the pain into power.",
    a: "Unknown",
    c: "25",
    h: "\u003Cblockquote\u003E&ldquo;Turn the pain into power.&rdquo; &mdash; \u003Cfooter\u003EUnknown\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Don't look back - you're not going that way.",
    a: "Mary Engelbreit",
    c: "44",
    h: "\u003Cblockquote\u003E&ldquo;Don't look back - you're not going that way.&rdquo; &mdash; \u003Cfooter\u003EMary Engelbreit\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "In order to carry a positive action, we must develop here a positive vision.",
    a: "Dalai Lama",
    c: "76",
    h: "\u003Cblockquote\u003E&ldquo;In order to carry a positive action, we must develop here a positive vision.&rdquo; &mdash; \u003Cfooter\u003EDalai Lama\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "The destiny of man is in his own soul. ",
    a: "Herodotus",
    c: "39",
    h: "\u003Cblockquote\u003E&ldquo;The destiny of man is in his own soul. &rdquo; &mdash; \u003Cfooter\u003EHerodotus\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "A loving heart is the truest wisdom.",
    a: "Charles Dickens",
    c: "36",
    h: "\u003Cblockquote\u003E&ldquo;A loving heart is the truest wisdom.&rdquo; &mdash; \u003Cfooter\u003ECharles Dickens\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "We can have more than we've got because we can become more than we are.",
    a: "Jim Rohn",
    c: "71",
    h: "\u003Cblockquote\u003E&ldquo;We can have more than we've got because we can become more than we are.&rdquo; &mdash; \u003Cfooter\u003EJim Rohn\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Re-examine all that you have been told... dismiss that which insults your soul.",
    a: "Walt Whitman",
    c: "79",
    h: "\u003Cblockquote\u003E&ldquo;Re-examine all that you have been told... dismiss that which insults your soul.&rdquo; &mdash; \u003Cfooter\u003EWalt Whitman\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "We think too much and feel too little.",
    a: "Charlie Chaplin",
    c: "38",
    h: "\u003Cblockquote\u003E&ldquo;We think too much and feel too little.&rdquo; &mdash; \u003Cfooter\u003ECharlie Chaplin\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "You are not stuck where you are unless you decide to be.  ",
    a: "Wayne Dyer",
    c: "58",
    h: "\u003Cblockquote\u003E&ldquo;You are not stuck where you are unless you decide to be.  &rdquo; &mdash; \u003Cfooter\u003EWayne Dyer\u003C/footer\u003E\u003C/blockquote\u003E",
  },
  {
    q: "Learn to use your emotions to think, not think with your emotions.",
    a: "Robert Kiyosaki",
    c: "66",
    h: "\u003Cblockquote\u003E&ldquo;Learn to use your emotions to think, not think with your emotions.&rdquo; &mdash; \u003Cfooter\u003ERobert Kiyosaki\u003C/footer\u003E\u003C/blockquote\u003E",
  },
];
